title: "Solomon Smith - AI & Software Engineer"
description: "Portfolio of Solomon Smith, an aspiring AI engineer with a focus on machine learning, full-stack development, and systems programming."
author: "Solomon Smith"
url: "https://solomon-smith-dev.tech"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

seo:
  title: "Solomon Smith - AI Engineer"
  description: "Portfolio of Solomon Smith, a computer science student and AI engineer in training, working with ML, C++, and full-stack development."
  keywords: "AI, Machine Learning, Deep Learning, Software Engineer, Full-Stack Developer, Solomon Smith, FastAPI, PyTorch"

