# Open Graph metadata for better social media sharing
title: "Solomon Smith - Software Engineer"
description: "Explore Solomon Smith's portfolio of projects in software engineering, full-stack development, and cybersecurity."
author: "Solomon Smith"
url: "https://solomon-smith-dev.tech"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# SEO meta tags
seo:
  title: "Solomon Smith"
  description: "Portfolio of Solomon Smith, a full-stack software engineer specializing in web development."
  keywords: "Software Engineer, Full-Stack Developer, Cybersecurity, Portfolio, Solomon Smith"
