title: "Solomon Smith"
description: "Portfolio of Solomon Smith — aspiring AI engineer and software developer."
name: "Solomon Smith"
url: "https://solomon-smith-dev.tech"
baseurl: ""

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# SEO
author:
  name: "Solomon Smith"
  avatar: "/assets/images/avatar.png"
  bio: "Computer Science major focused on AI, ML, and full-stack engineering."
  location: "California, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SolomonSmith-dev"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/solomonsmithdev/"

# Navigation
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/
